server:
  address: localhost
  port: 8849
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    data-username:
#    data-password:
#    url:
#  redis:
#    host: localhost
#    port: 6379
#    username:
#    password: