server:
  port: 8948
  servlet:
    context-path: /
spring:
  security:
    user:
      name: wangdh
      password: 123456
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demoschema?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

