server:
  port: 8948
  servlet:
    context-path: /
spring:
  security:
    user:
      name: wangdh
      password: 123456
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://81.68.251.200:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: nacos
    password: nacos
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 81.68.251.200
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 81.68.251.200:8848

