server:
  address: localhost
  port: 8848
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-username: root
    data-password: root
    hikari:
      jdbc-url: jdbc:mysql://81.68.251.200:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  profiles:
    active: dev
#  redis:
#    host: localhost
#    port: 6379
#    username:
#    password: